### PR TITLE
Fix persistent game config

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by AsciiWolf** [comment]
The config file is now properly saved, sound sadly still does not work.

**Comment by AsciiWolf** [comment]
Config is now properly saved. @hfiguiere Feel free to merge.

I have created a [ticket](https://github.com/flathub/de.billardgl.Billardgl/issues/10) for the sound issue.

**Comment by AsciiWolf** [comment]
@hfiguiere I was thinking about another possible solution: Using a startup script that creates a symlink to a persistent directory on startup. However, the solution with making the whole home persistent is probably a better one.

**Comment by hfiguiere** [comment]
@AsciiWolf shall @barthalion invite you to this repo since it doesn't seem to have maintainer?

**Comment by AsciiWolf** [comment]
Thanks for the offer, but probably not at the moment. I already maintain too many (30) Flatpaks and have too little time. :-)

**Pull request merged**
