### PR TITLE
Update runtime to 22.08

### LINKED ISSUE #6: Update the runtime to 22.08
Consider updating the org.freedesktop.Platform runtime used by this Flatpak to 22.08.

### PR DESCRIPTION
**Pull request by AsciiWolf**
Closes #6.

### CODE REVIEW

**Comment by AsciiWolf** [comment]
Tested and works fine:

screenshot

@hfiguiere Feel free to merge.

The only two issues are that:
1. There is no sound support (it is a game from 2003 so it most likely requires OSS or similar old system).
2. Config is not saved because it is created directly in `~/` (so it cannot be made persistent with `--persist`).

However, both these issues are also present in the older build with 21.08 fd runtime.

**Comment by hfiguiere** [comment]
You could `--persist=.`, this would save the whole home. (empty initially).

As for the sound, maybe `--device=all`, as **if** it's OSS it will use `/dev/dsp`

**Comment by hfiguiere** [comment]
I can't find where it has sound support

**Comment by hfiguiere** [comment]
merging this. the other problem can be worked out later.

**Pull request merged**
